name : Workflow deployment TaxiFare

permissions:
  contents: read

run-name : Workflow deployment TaxiFare
on : [push, workflow_dispatch]

jobs:
  TaxiFare:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      
      - name: Step 1 - Setup NodeJS
        uses: actions/setup-node@v6
        with:
            node-version: 24
            cache: npm

      - name: Installation des dépendances
        run: npm i